/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Module {
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface Order {
  'customerName' : string,
  'color' : string,
  'selectedModules' : Array<string>,
  'productType' : string,
  'email' : string,
  'orderId' : bigint,
  'address' : string,
  'quantity' : bigint,
  'phone' : string,
  'totalPrice' : bigint,
  'material' : string,
  'product' : Product,
}
export interface Product {
  'basePriceDigital' : bigint,
  'name' : string,
  'description' : string,
  'basePricePhysical' : bigint,
}
export interface _SERVICE {
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAvailableModules' : ActorMethod<[], Array<Module>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[], Product>,
  'placeOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      bigint,
      string,
      bigint,
    ],
    { 'orderId' : bigint, 'totalPrice' : bigint }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];