/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'basePriceDigital' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'basePricePhysical' : IDL.Nat,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'color' : IDL.Text,
  'selectedModules' : IDL.Vec(IDL.Text),
  'productType' : IDL.Text,
  'email' : IDL.Text,
  'orderId' : IDL.Nat,
  'address' : IDL.Text,
  'quantity' : IDL.Nat,
  'phone' : IDL.Text,
  'totalPrice' : IDL.Nat,
  'material' : IDL.Text,
  'product' : Product,
});
export const Module = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAvailableModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([], [Product], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Record({ 'orderId' : IDL.Nat, 'totalPrice' : IDL.Nat })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'basePriceDigital' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'basePricePhysical' : IDL.Nat,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'color' : IDL.Text,
    'selectedModules' : IDL.Vec(IDL.Text),
    'productType' : IDL.Text,
    'email' : IDL.Text,
    'orderId' : IDL.Nat,
    'address' : IDL.Text,
    'quantity' : IDL.Nat,
    'phone' : IDL.Text,
    'totalPrice' : IDL.Nat,
    'material' : IDL.Text,
    'product' : Product,
  });
  const Module = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAvailableModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([], [Product], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Record({ 'orderId' : IDL.Nat, 'totalPrice' : IDL.Nat })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };